### ISSUE TITLE
ffi-1.11.1 fails to build on Mac OS X 10.13.6 High Sierra

### ISSUE THREAD

**Issue by garethgreenaway** [ffi/ffi#702]
Attempting to install ffi on OS X today resulted in the following, work around right now is pinning to 1.10.x.

```
'ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
Undefined symbols for architecture i386:
  "___x86.get_pc_thunk.bx", referenced from:
      _ffi_call_i386 in sysv.o
      _ffi_closure_raw_SYSV in sysv.o
      _ffi_closure_raw_THISCALL in sysv.o
  "___x86.get_pc_thunk.dx", referenced from:
      _ffi_closure_i386 in sysv.o
      _ffi_closure_STDCALL in sysv.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libffi.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** ["/Library/Ruby/Gems/2.3.0/gems/ffi-1.11.1/ext/ffi_c"/libffi-i386/.libs/libffi_convenience.a] Error 2

make failed, exit code 2
```

**Comment by sxzheng** [comment]
I fixed this problem with updating my ruby from 2.3.7 to 2.6.3. hope it works for you.

**Comment by hequn8128** [comment]
thanks to @sxzheng , updating the ruby version also works for me.
