### ISSUE TITLE
ffi 1.11 fails to build on ruby 1.9.3

### ISSUE THREAD

**Issue by aflat** [ffi/ffi#699]
I can't build fpm on centos6 because it requires me to build ruby 1.9.3. I can compile ruby 1.9.3, then I try to gem install fpm, which depends on ffi. When it tries to compile ffi 1.11 it fails

```
make[3]: Leaving directory `/usr/local/lib/ruby/gems/1.9.1/gems/ffi-1.11.0/ext/ffi_c/libffi-x86_64-linux'
make[2]: Leaving directory `/usr/local/lib/ruby/gems/1.9.1/gems/ffi-1.11.0/ext/ffi_c/libffi-
make[1]: Leaving directory `/usr/local/lib/ruby/gems/1.9.1/gems/ffi-1.11.0/ext/ffi_c/libffi-x86_64-linux'
compiling Pointer.c
compiling Platform.c
compiling StructLayout.c
compiling Buffer.c
compiling MethodHandle.c
compiling LongDouble.c
compiling Type.c
compiling StructByValue.c
compiling Call.c
Call.c:46:25: error: ruby/thread.h: No such file or directory
```

using ffi 1.10 works fine.

**Comment by larskanis** [comment]
ffi-1.11.0 will no longer work on Ruby-1.9. We removed the old compatibility code in #683 . I just forgot to raise the ruby version requirement [in the gemspec](https://github.com/ffi/ffi/commit/08b9b7875fe6fff8ba34d794a4bdebaf78b95ba2). You'll have to stay at ffi-1.10.0 or update ruby.

**Comment by mvz** [comment]
How about testing down to version 2.0 on Travis to avoid this happening in the future?
