### ISSUE TITLE
Can't build on Ubuntu 14.04 x86

### ISSUE THREAD

**Issue by slavafomin** [ffi/ffi#414]
Hello!

I've tried to install Compass using `sudo gem install compass`, but encountered a problem with FFI.

Here's the additional details (please see both my question and answer):
http://stackoverflow.com/q/29046417/1056679

I'm sorry, I couldn't provide more detailed diagnostic of the problem.

Thank you.

**Comment by marutosi** [comment]
Redmine official CI server ([Ubuntu 11.10 (GNU/Linux 3.0.0-12-generic-pae i686)](http://www.redmine.org/projects/redmine/wiki/Continuous_integration) fails to install  ffi-1.9.7.

http://www.redmine.org/builds/logs/build_trunk_mysql_ruby-2.2_2400.html
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /var/lib/jenkins/ruby/ruby-2.2.0/bin/ruby -r ./siteconf20150314-17390-7iupbv.rb extconf.rb 
checking for ffi_call() in -lffi... yes
checking for ffi_prep_closure()... yes
checking for ffi_raw_call()... yes
checking for ffi_prep_raw_closure()... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... yes
creating extconf.h
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling Types.c
compiling StructByReference.c
compiling Function.c
compiling StructLayout.c
compiling Call.c
Call.c: In function ‘rbffi_SetupCallParams’:
Call.c:206:1: error: ‘UINT32_ADJ’ undeclared (first use in this function)
Call.c:206:1: note: each undeclared identifier is reported only once for each function it appears in
Call.c:230:1: error: ‘UINT64_ADJ’ undeclared (first use in this function)
make: *** [Call.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/jenkins/ruby/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/ffi-1.9.7 for inspection.
Results logged to /var/lib/jenkins/ruby/ruby-2.2.0/lib/ruby/gems/2.2.0/extensions/x86-linux/2.2.0-static/ffi-1.9.7/gem_make.out
An error occurred while installing ffi (1.9.7), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.7'` succeeds before bundling.
```

**Comment by usctrojan** [comment]
+1

Same problem here.

**Comment by jasnow** [comment]
I got the problem too.

**Comment by mistic100** [comment]
If someone here is trying to install `github-pages` with Bundle like me, simply add `gem 'ffi', '1.9.6'` to your Gemfile to force the previous working version

**Comment by tduehr** [comment]
1.9.8 fixes this issue in 1.9.7 which has been yanked

**Comment by marutosi** [comment]
Not fix #418.

**Comment by jasnow** [comment]
Thank you - rebuilt my projects and they all worked.
