### ISSUE TITLE
1.0.2 fails to build on Ubuntu Natty Alpha 1 / Ruby 1.9.3dev

### ISSUE THREAD

**Issue by colindean** [ffi/ffi#69]
<pre>/home/colin/.rvm/rubies/ruby-head/bin/ruby extconf.rb
extconf.rb:6: Use RbConfig instead of obsolete and deprecated Config.
checking for ffi.h in /usr/local/include... no
checking for rb_thread_blocking_region()... yes
checking for ruby_thread_has_gvl_p()... yes
checking for ruby_native_thread_p()... yes
checking for rb_thread_call_with_gvl()... yes
creating extconf.h
creating Makefile

make
compiling StructLayout.c
compiling Call.c
compiling LastError.c
compiling StructByValue.c
compiling ClosurePool.c
compiling Platform.c
compiling Buffer.c
compiling DynamicLibrary.c
compiling DataConverter.c
compiling Struct.c
Struct.c: In function ‘struct_set_pointer’:
Struct.c:288:36: warning: comparison between signed and unsigned integer expressions
Struct.c: In function ‘inline_array_offset’:
Struct.c:425:28: warning: comparison between signed and unsigned integer expressions
Struct.c: In function ‘inline_array_each’:
Struct.c:515:19: warning: comparison between signed and unsigned integer expressions
Struct.c: In function ‘inline_array_to_a’:
Struct.c:533:19: warning: comparison between signed and unsigned integer expressions
compiling StructByReference.c
compiling Pointer.c
compiling AbstractMemory.c
AbstractMemory.c: In function ‘memory_get_array_of_int8’:
AbstractMemory.c:225:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_get_array_of_uint8’:
AbstractMemory.c:226:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_get_array_of_int16’:
AbstractMemory.c:227:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_get_array_of_uint16’:
AbstractMemory.c:228:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_op_put_int32’:
AbstractMemory.c:229:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_op_get_int32’:
AbstractMemory.c:229:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_put_array_of_int32’:
AbstractMemory.c:229:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_get_array_of_int32’:
AbstractMemory.c:229:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c:229:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_get_array_of_uint32’:
AbstractMemory.c:230:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_op_put_int64’:
AbstractMemory.c:231:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_op_get_int64’:
AbstractMemory.c:231:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_put_array_of_int64’:
AbstractMemory.c:231:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_get_array_of_int64’:
AbstractMemory.c:231:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c:231:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_get_array_of_uint64’:
AbstractMemory.c:232:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_op_put_long’:
AbstractMemory.c:233:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_op_get_long’:
AbstractMemory.c:233:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_put_array_of_long’:
AbstractMemory.c:233:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_get_array_of_long’:
AbstractMemory.c:233:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c:233:1: warning: signed and unsigned type in conditional expression
AbstractMemory.c: In function ‘memory_get_array_of_ulong’:
AbstractMemory.c:234:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_get_array_of_float32’:
AbstractMemory.c:235:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_get_array_of_float64’:
AbstractMemory.c:236:1: error: ISO C90 forbids mixed declarations and code
AbstractMemory.c: In function ‘memory_get_array_of_pointer’:
AbstractMemory.c:258:1: error: ISO C90 forbids mixed declarations and code
make: *** [AbstractMemory.o] Error 1</pre>

<pre>[colin@bricktop plas]$ gem --version
1.3.7
[colin@bricktop plas]$ ruby --version
ruby 1.9.3dev (2010-12-18 trunk 30244) [x86_64-linux]
[colin@bricktop plas]$ dpkg --list | grep bz2
ii  libbz2-1.0                                1.0.5-6                                    high-quality block-sorting file compressor library - runtime
ii  libbz2-dev                                1.0.5-6                                    high-quality block-sorting file compressor library - development
[colin@bricktop plas]$ lsb_release -dr
Description:    Ubuntu natty (development branch)
Release:    11.04</pre>
